/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SigninRouteImport } from './routes/signin'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ResourcesRouteImport } from './routes/resources'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as PaywallRouteImport } from './routes/paywall'
import { Route as HomeRouteImport } from './routes/home'
import { Route as HistoryRouteImport } from './routes/history'
import { Route as ForyouRouteImport } from './routes/foryou'
import { Route as CheckoutReturnRouteImport } from './routes/checkout-return'
import { Route as CheckinRouteImport } from './routes/checkin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ExploreIndexRouteImport } from './routes/explore.index'
import { Route as ToolKeyRouteImport } from './routes/tool.$key'
import { Route as ResetTileRouteImport } from './routes/reset.$tile'
import { Route as MetooTileRouteImport } from './routes/metoo.$tile'
import { Route as ExploreCatRouteImport } from './routes/explore.$cat'
import { Route as LovableEmailTransactionalPreviewRouteImport } from './routes/lovable/email/transactional/preview'
import { Route as ApiPublicPaymentsWebhookRouteImport } from './routes/api/public/payments/webhook'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SigninRoute = SigninRouteImport.update({
  id: '/signin',
  path: '/signin',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ResourcesRoute = ResourcesRouteImport.update({
  id: '/resources',
  path: '/resources',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const PaywallRoute = PaywallRouteImport.update({
  id: '/paywall',
  path: '/paywall',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeRoute = HomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryRoute = HistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => rootRouteImport,
} as any)
const ForyouRoute = ForyouRouteImport.update({
  id: '/foryou',
  path: '/foryou',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutReturnRoute = CheckoutReturnRouteImport.update({
  id: '/checkout-return',
  path: '/checkout-return',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckinRoute = CheckinRouteImport.update({
  id: '/checkin',
  path: '/checkin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ExploreIndexRoute = ExploreIndexRouteImport.update({
  id: '/explore/',
  path: '/explore/',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolKeyRoute = ToolKeyRouteImport.update({
  id: '/tool/$key',
  path: '/tool/$key',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetTileRoute = ResetTileRouteImport.update({
  id: '/reset/$tile',
  path: '/reset/$tile',
  getParentRoute: () => rootRouteImport,
} as any)
const MetooTileRoute = MetooTileRouteImport.update({
  id: '/metoo/$tile',
  path: '/metoo/$tile',
  getParentRoute: () => rootRouteImport,
} as any)
const ExploreCatRoute = ExploreCatRouteImport.update({
  id: '/explore/$cat',
  path: '/explore/$cat',
  getParentRoute: () => rootRouteImport,
} as any)
const LovableEmailTransactionalPreviewRoute =
  LovableEmailTransactionalPreviewRouteImport.update({
    id: '/lovable/email/transactional/preview',
    path: '/lovable/email/transactional/preview',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicPaymentsWebhookRoute =
  ApiPublicPaymentsWebhookRouteImport.update({
    id: '/api/public/payments/webhook',
    path: '/api/public/payments/webhook',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/checkin': typeof CheckinRoute
  '/checkout-return': typeof CheckoutReturnRoute
  '/foryou': typeof ForyouRoute
  '/history': typeof HistoryRoute
  '/home': typeof HomeRoute
  '/paywall': typeof PaywallRoute
  '/privacy': typeof PrivacyRoute
  '/resources': typeof ResourcesRoute
  '/settings': typeof SettingsRoute
  '/signin': typeof SigninRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/explore/$cat': typeof ExploreCatRoute
  '/metoo/$tile': typeof MetooTileRoute
  '/reset/$tile': typeof ResetTileRoute
  '/tool/$key': typeof ToolKeyRoute
  '/explore/': typeof ExploreIndexRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/checkin': typeof CheckinRoute
  '/checkout-return': typeof CheckoutReturnRoute
  '/foryou': typeof ForyouRoute
  '/history': typeof HistoryRoute
  '/home': typeof HomeRoute
  '/paywall': typeof PaywallRoute
  '/privacy': typeof PrivacyRoute
  '/resources': typeof ResourcesRoute
  '/settings': typeof SettingsRoute
  '/signin': typeof SigninRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/explore/$cat': typeof ExploreCatRoute
  '/metoo/$tile': typeof MetooTileRoute
  '/reset/$tile': typeof ResetTileRoute
  '/tool/$key': typeof ToolKeyRoute
  '/explore': typeof ExploreIndexRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/checkin': typeof CheckinRoute
  '/checkout-return': typeof CheckoutReturnRoute
  '/foryou': typeof ForyouRoute
  '/history': typeof HistoryRoute
  '/home': typeof HomeRoute
  '/paywall': typeof PaywallRoute
  '/privacy': typeof PrivacyRoute
  '/resources': typeof ResourcesRoute
  '/settings': typeof SettingsRoute
  '/signin': typeof SigninRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/explore/$cat': typeof ExploreCatRoute
  '/metoo/$tile': typeof MetooTileRoute
  '/reset/$tile': typeof ResetTileRoute
  '/tool/$key': typeof ToolKeyRoute
  '/explore/': typeof ExploreIndexRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/checkin'
    | '/checkout-return'
    | '/foryou'
    | '/history'
    | '/home'
    | '/paywall'
    | '/privacy'
    | '/resources'
    | '/settings'
    | '/signin'
    | '/sitemap.xml'
    | '/terms'
    | '/explore/$cat'
    | '/metoo/$tile'
    | '/reset/$tile'
    | '/tool/$key'
    | '/explore/'
    | '/api/public/payments/webhook'
    | '/lovable/email/transactional/preview'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/checkin'
    | '/checkout-return'
    | '/foryou'
    | '/history'
    | '/home'
    | '/paywall'
    | '/privacy'
    | '/resources'
    | '/settings'
    | '/signin'
    | '/sitemap.xml'
    | '/terms'
    | '/explore/$cat'
    | '/metoo/$tile'
    | '/reset/$tile'
    | '/tool/$key'
    | '/explore'
    | '/api/public/payments/webhook'
    | '/lovable/email/transactional/preview'
  id:
    | '__root__'
    | '/'
    | '/checkin'
    | '/checkout-return'
    | '/foryou'
    | '/history'
    | '/home'
    | '/paywall'
    | '/privacy'
    | '/resources'
    | '/settings'
    | '/signin'
    | '/sitemap.xml'
    | '/terms'
    | '/explore/$cat'
    | '/metoo/$tile'
    | '/reset/$tile'
    | '/tool/$key'
    | '/explore/'
    | '/api/public/payments/webhook'
    | '/lovable/email/transactional/preview'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CheckinRoute: typeof CheckinRoute
  CheckoutReturnRoute: typeof CheckoutReturnRoute
  ForyouRoute: typeof ForyouRoute
  HistoryRoute: typeof HistoryRoute
  HomeRoute: typeof HomeRoute
  PaywallRoute: typeof PaywallRoute
  PrivacyRoute: typeof PrivacyRoute
  ResourcesRoute: typeof ResourcesRoute
  SettingsRoute: typeof SettingsRoute
  SigninRoute: typeof SigninRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TermsRoute: typeof TermsRoute
  ExploreCatRoute: typeof ExploreCatRoute
  MetooTileRoute: typeof MetooTileRoute
  ResetTileRoute: typeof ResetTileRoute
  ToolKeyRoute: typeof ToolKeyRoute
  ExploreIndexRoute: typeof ExploreIndexRoute
  ApiPublicPaymentsWebhookRoute: typeof ApiPublicPaymentsWebhookRoute
  LovableEmailTransactionalPreviewRoute: typeof LovableEmailTransactionalPreviewRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signin': {
      id: '/signin'
      path: '/signin'
      fullPath: '/signin'
      preLoaderRoute: typeof SigninRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resources': {
      id: '/resources'
      path: '/resources'
      fullPath: '/resources'
      preLoaderRoute: typeof ResourcesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/paywall': {
      id: '/paywall'
      path: '/paywall'
      fullPath: '/paywall'
      preLoaderRoute: typeof PaywallRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home': {
      id: '/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history': {
      id: '/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof HistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/foryou': {
      id: '/foryou'
      path: '/foryou'
      fullPath: '/foryou'
      preLoaderRoute: typeof ForyouRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout-return': {
      id: '/checkout-return'
      path: '/checkout-return'
      fullPath: '/checkout-return'
      preLoaderRoute: typeof CheckoutReturnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkin': {
      id: '/checkin'
      path: '/checkin'
      fullPath: '/checkin'
      preLoaderRoute: typeof CheckinRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explore/': {
      id: '/explore/'
      path: '/explore'
      fullPath: '/explore/'
      preLoaderRoute: typeof ExploreIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tool/$key': {
      id: '/tool/$key'
      path: '/tool/$key'
      fullPath: '/tool/$key'
      preLoaderRoute: typeof ToolKeyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset/$tile': {
      id: '/reset/$tile'
      path: '/reset/$tile'
      fullPath: '/reset/$tile'
      preLoaderRoute: typeof ResetTileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/metoo/$tile': {
      id: '/metoo/$tile'
      path: '/metoo/$tile'
      fullPath: '/metoo/$tile'
      preLoaderRoute: typeof MetooTileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explore/$cat': {
      id: '/explore/$cat'
      path: '/explore/$cat'
      fullPath: '/explore/$cat'
      preLoaderRoute: typeof ExploreCatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/transactional/preview': {
      id: '/lovable/email/transactional/preview'
      path: '/lovable/email/transactional/preview'
      fullPath: '/lovable/email/transactional/preview'
      preLoaderRoute: typeof LovableEmailTransactionalPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/payments/webhook': {
      id: '/api/public/payments/webhook'
      path: '/api/public/payments/webhook'
      fullPath: '/api/public/payments/webhook'
      preLoaderRoute: typeof ApiPublicPaymentsWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CheckinRoute: CheckinRoute,
  CheckoutReturnRoute: CheckoutReturnRoute,
  ForyouRoute: ForyouRoute,
  HistoryRoute: HistoryRoute,
  HomeRoute: HomeRoute,
  PaywallRoute: PaywallRoute,
  PrivacyRoute: PrivacyRoute,
  ResourcesRoute: ResourcesRoute,
  SettingsRoute: SettingsRoute,
  SigninRoute: SigninRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TermsRoute: TermsRoute,
  ExploreCatRoute: ExploreCatRoute,
  MetooTileRoute: MetooTileRoute,
  ResetTileRoute: ResetTileRoute,
  ToolKeyRoute: ToolKeyRoute,
  ExploreIndexRoute: ExploreIndexRoute,
  ApiPublicPaymentsWebhookRoute: ApiPublicPaymentsWebhookRoute,
  LovableEmailTransactionalPreviewRoute: LovableEmailTransactionalPreviewRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
