/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ResourcesRouteImport } from './routes/resources'
import { Route as PaywallRouteImport } from './routes/paywall'
import { Route as HistoryRouteImport } from './routes/history'
import { Route as CheckoutReturnRouteImport } from './routes/checkout-return'
import { Route as CheckinRouteImport } from './routes/checkin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ResetTileRouteImport } from './routes/reset.$tile'
import { Route as MetooTileRouteImport } from './routes/metoo.$tile'
import { Route as LovableEmailTransactionalPreviewRouteImport } from './routes/lovable/email/transactional/preview'
import { Route as ApiPublicPaymentsWebhookRouteImport } from './routes/api/public/payments/webhook'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ResourcesRoute = ResourcesRouteImport.update({
  id: '/resources',
  path: '/resources',
  getParentRoute: () => rootRouteImport,
} as any)
const PaywallRoute = PaywallRouteImport.update({
  id: '/paywall',
  path: '/paywall',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryRoute = HistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutReturnRoute = CheckoutReturnRouteImport.update({
  id: '/checkout-return',
  path: '/checkout-return',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckinRoute = CheckinRouteImport.update({
  id: '/checkin',
  path: '/checkin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetTileRoute = ResetTileRouteImport.update({
  id: '/reset/$tile',
  path: '/reset/$tile',
  getParentRoute: () => rootRouteImport,
} as any)
const MetooTileRoute = MetooTileRouteImport.update({
  id: '/metoo/$tile',
  path: '/metoo/$tile',
  getParentRoute: () => rootRouteImport,
} as any)
const LovableEmailTransactionalPreviewRoute =
  LovableEmailTransactionalPreviewRouteImport.update({
    id: '/lovable/email/transactional/preview',
    path: '/lovable/email/transactional/preview',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicPaymentsWebhookRoute =
  ApiPublicPaymentsWebhookRouteImport.update({
    id: '/api/public/payments/webhook',
    path: '/api/public/payments/webhook',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/checkin': typeof CheckinRoute
  '/checkout-return': typeof CheckoutReturnRoute
  '/history': typeof HistoryRoute
  '/paywall': typeof PaywallRoute
  '/resources': typeof ResourcesRoute
  '/settings': typeof SettingsRoute
  '/metoo/$tile': typeof MetooTileRoute
  '/reset/$tile': typeof ResetTileRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/checkin': typeof CheckinRoute
  '/checkout-return': typeof CheckoutReturnRoute
  '/history': typeof HistoryRoute
  '/paywall': typeof PaywallRoute
  '/resources': typeof ResourcesRoute
  '/settings': typeof SettingsRoute
  '/metoo/$tile': typeof MetooTileRoute
  '/reset/$tile': typeof ResetTileRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/checkin': typeof CheckinRoute
  '/checkout-return': typeof CheckoutReturnRoute
  '/history': typeof HistoryRoute
  '/paywall': typeof PaywallRoute
  '/resources': typeof ResourcesRoute
  '/settings': typeof SettingsRoute
  '/metoo/$tile': typeof MetooTileRoute
  '/reset/$tile': typeof ResetTileRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/checkin'
    | '/checkout-return'
    | '/history'
    | '/paywall'
    | '/resources'
    | '/settings'
    | '/metoo/$tile'
    | '/reset/$tile'
    | '/api/public/payments/webhook'
    | '/lovable/email/transactional/preview'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/checkin'
    | '/checkout-return'
    | '/history'
    | '/paywall'
    | '/resources'
    | '/settings'
    | '/metoo/$tile'
    | '/reset/$tile'
    | '/api/public/payments/webhook'
    | '/lovable/email/transactional/preview'
  id:
    | '__root__'
    | '/'
    | '/checkin'
    | '/checkout-return'
    | '/history'
    | '/paywall'
    | '/resources'
    | '/settings'
    | '/metoo/$tile'
    | '/reset/$tile'
    | '/api/public/payments/webhook'
    | '/lovable/email/transactional/preview'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CheckinRoute: typeof CheckinRoute
  CheckoutReturnRoute: typeof CheckoutReturnRoute
  HistoryRoute: typeof HistoryRoute
  PaywallRoute: typeof PaywallRoute
  ResourcesRoute: typeof ResourcesRoute
  SettingsRoute: typeof SettingsRoute
  MetooTileRoute: typeof MetooTileRoute
  ResetTileRoute: typeof ResetTileRoute
  ApiPublicPaymentsWebhookRoute: typeof ApiPublicPaymentsWebhookRoute
  LovableEmailTransactionalPreviewRoute: typeof LovableEmailTransactionalPreviewRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resources': {
      id: '/resources'
      path: '/resources'
      fullPath: '/resources'
      preLoaderRoute: typeof ResourcesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/paywall': {
      id: '/paywall'
      path: '/paywall'
      fullPath: '/paywall'
      preLoaderRoute: typeof PaywallRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history': {
      id: '/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof HistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout-return': {
      id: '/checkout-return'
      path: '/checkout-return'
      fullPath: '/checkout-return'
      preLoaderRoute: typeof CheckoutReturnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkin': {
      id: '/checkin'
      path: '/checkin'
      fullPath: '/checkin'
      preLoaderRoute: typeof CheckinRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset/$tile': {
      id: '/reset/$tile'
      path: '/reset/$tile'
      fullPath: '/reset/$tile'
      preLoaderRoute: typeof ResetTileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/metoo/$tile': {
      id: '/metoo/$tile'
      path: '/metoo/$tile'
      fullPath: '/metoo/$tile'
      preLoaderRoute: typeof MetooTileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/transactional/preview': {
      id: '/lovable/email/transactional/preview'
      path: '/lovable/email/transactional/preview'
      fullPath: '/lovable/email/transactional/preview'
      preLoaderRoute: typeof LovableEmailTransactionalPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/payments/webhook': {
      id: '/api/public/payments/webhook'
      path: '/api/public/payments/webhook'
      fullPath: '/api/public/payments/webhook'
      preLoaderRoute: typeof ApiPublicPaymentsWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CheckinRoute: CheckinRoute,
  CheckoutReturnRoute: CheckoutReturnRoute,
  HistoryRoute: HistoryRoute,
  PaywallRoute: PaywallRoute,
  ResourcesRoute: ResourcesRoute,
  SettingsRoute: SettingsRoute,
  MetooTileRoute: MetooTileRoute,
  ResetTileRoute: ResetTileRoute,
  ApiPublicPaymentsWebhookRoute: ApiPublicPaymentsWebhookRoute,
  LovableEmailTransactionalPreviewRoute: LovableEmailTransactionalPreviewRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
